const path = require('path')

const SRC_ROOT = `../../src/chapter3/`
const { isNull, car, pair } = require(path.join(SRC_ROOT, 'utils'))

const {
  memo,
  stream_cdr, stream_ref,
  stream_map
} = require(path.join(SRC_ROOT, 'ch3-5-1'))

const { solve } = require(path.join(SRC_ROOT, 'ch3-5-4'))

describe('chapter 3-5-4', () => {
  it('approximate e', () => {
    const e = stream_ref(solve(y => y, 1, 0.001), 1000)
    expect(e > 2.71 && e < 2.72).toBe(true)
  })
})

describe('chapter 3-5-4 execises', () => {
  it('exec3.77', () => {
    function integral(integrand, initial_value, dt) {
      return pair(
        initial_value,
        memo(
          () => {
            const eval_integrand = integrand()
            return isNull(eval_integrand)
              ? null
              : integral(
                () => stream_cdr(eval_integrand),
                car(eval_integrand) * dt + initial_value,
                dt
              )
          }
        )
      )
    }

    function solve(f, y0, dt) {
      const y = integral(() => dy, y0, dt)
      const dy = stream_map(f, y)

      return y
    }

    const e = stream_ref(solve(y => y, 1, 0.001), 1000)
    expect(e > 2.71 && e < 2.72).toBe(true)
  })

/*
  Sorry, I know nothing about INTEGRAL...

  Exercise 3.78
    Consider the problem of designing a signal-processing system to study the homogeneous
    second-order linear differential equation
      d2y
      dt2 – a
      dy
      dt
      – by = 0
    The output stream, modeling y, is generated by a network that contains a loop. This is
    because the value of d2y/dt2 depends upon the values of y and dy/dt and both of these
    are determined by integrating d2y/dt2. The diagram we would like to encode is shown in
    figure 3.35. Write a function solve_2nd that takes as arguments the constants a, b, and
    dt and the initial values y0 and dy0 for y and dy/dt and generates the stream of successive
    values of y.

  Exercise 3.79
    Generalize the solve_2nd function of exercise 3.78 so that it can be used to solve general
    second-order differential equations d2y/dt2 = f (dy/dt, y).

  Exercise 3.80
*/
})
